# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a6296a74f3a1467addd020a3d88e16eebcc83e1abfa811841ee495a4d4de190eca8e95f0d96f40ac48dbffaa86824198412c6c6b4f9f237c94b61d990e83ff90

test:
  secret_key_base: c9e16d007d8891cf56400029254c0333d5ffec77d481b7364190cfc98abc563528ce8ce1d384e15342d1d1ae3266e26eb9c4d1a1496f0ec658e5a2ead21c0ca9

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
